# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - name: sample-node-app
        image: my-private-registry/sample-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: sample-node-app
spec:
  ports:
  - port: 3000
    nodePort: 31234
  selector:
    app: sample-node-app
  type: NodePort
